# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kyototycoon}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["uu59"]
  s.date = %q{2010-12-09}
  s.description = %q{KyotoTycoon client for Ruby}
  s.email = %q{a@tt25.org}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "benchmark/agent.rb",
    "benchmark/bulk.rb",
    "benchmark/bulk_bigdata.rb",
    "benchmark/getset.rb",
    "benchmark/getset_while_1sec.rb",
    "kyototycoon.gemspec",
    "lib/kyototycoon.rb",
    "lib/kyototycoon/serializer.rb",
    "lib/kyototycoon/serializer/default.rb",
    "lib/kyototycoon/serializer/msgpack.rb",
    "lib/kyototycoon/tsvrpc.rb",
    "lib/kyototycoon/tsvrpc/nethttp.rb",
    "lib/kyototycoon/tsvrpc/skinny.rb",
    "spec/helper.rb"
  ]
  s.homepage = %q{http://github.com/uu59/kyototycoon-ruby}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{KyotoTycoon client for Ruby}
  s.test_files = [
    "spec/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<msgpack>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<msgpack>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<msgpack>, [">= 0"])
  end
end

